### ISSUE TITLE
Bug: YAML serialization of git sha1

### ISSUE THREAD

**Issue by leafty** [jupyterhub/chartpress#15]
In the event that the git short hash of a repository is something like `01234567`, then the image tag is serialized unquoted, resulting in a broken `values.yaml`.

This is a bit hard to reproduce, as it would happen on only ~0.4% of the commits.

You can reproduce the issue by running:
```bash
git clone https://github.com/SwissDataScienceCenter/renku-ui
cd renku-ui
git checkout -b test 0192117
cd helm-chart
chartpress
```

Then, you can check the `values.yaml` file contents:
```bash
cat renku-ui/values.yaml
```
```yaml
[...]
image:
  name: renku/renku-ui
  repository: renku/renku-ui
  tag: 0192117
  pullPolicy: IfNotPresent
[...]
```

As you can see, this will result in `image.tag` equals to `192117` and not `0192117`.

A potential fix would be to always quote sha1 tags.
