### ISSUE TITLE
Chartpress lists the images form the first helm chart only

### ISSUE THREAD

**Issue by olevski** [jupyterhub/chartpress#240]
### Bug description

When there are multiple charts in one chartpress.yaml file then running `chartpress --list-images` shows only the images form the first chart. But it should show the images from all charts.

### How to reproduce

1. Take the chartpress.yaml file below.
2. Run `chartpress --list-images`
3. Filp the order of the charts in the file
4. Run `chartpress --list-images` again

```
charts:
  - name: helm-chart/amalthea-sessions
    resetTag: latest
    imagePrefix: renku/
    repo:
      git: SwissDataScienceCenter/helm-charts
      published: https://swissdatasciencecenter.github.io/helm-charts
    paths:
      - .
    images:
      amalthea-sessions:
        contextPath: .
        dockerfilePath: Dockerfile
        valuesPath: controllerManager.manager.image
      sidecars:
        contextPath: .
        dockerfilePath: sidecars.Dockerfile
        valuesPath: sidecars.image
  - name: helm-chart/amalthea
    resetTag: latest
    imagePrefix: renku/
    repo:
      git: SwissDataScienceCenter/helm-charts
      published: https://swissdatasciencecenter.github.io/helm-charts
    paths:
      - .
    images:
      amalthea:
        contextPath: .
        dockerfilePath: kopf.Dockerfile
        valuesPath: image

```

#### Expected behaviour

I should see the images from both charts, not just the first one

#### Actual behaviour

The images only from the first chart are listed

### Your personal set up

Linux  6.11.0-9-generic #9-Ubuntu x86_64 GNU/Linux
Installed via pipx: package chartpress 2.2.0, installed using Python 3.12.
Pipx version 1.7.1
