### ISSUE TITLE
using chartpress with pre-commit

### ISSUE THREAD

**Issue by rokroskar** [jupyterhub/chartpress#38]
I've started using `chartpress --reset` with the [pre-commit](https://pre-commit.com/) package and it works very nicely to prevent accidental commits of modified chart values. It would be great to have the `.pre-commit.hooks.yaml` definition as a part of chartpress so one could simply include it like any other pre-commit hook. The user of chartpress would then have a `.pre-commit.config.yaml` in their repo's base directory with something like:

```yaml
repos:
-   repo: https://github.com/jupyterhub/chartpress
    rev: master
    hooks:
    - id: chartpress
```

If then you try to commit a change to the chartpress-managed values you get something like:

```
git commit -am 'commiting something'
black................................................(no files to check)Skipped
Flake8...............................................(no files to check)Skipped
chartpress reset.........................................................Failed
hookid: chartpress
```

If you want to include something like this I'll happily contribute a PR.

**Comment by minrk** [comment]
chartpress is often pretty expensive to run, which can be quite frustrating for pre-commit hooks, which need to be very quick to avoid causing friction. But it would at least be interesting to see an example

**Comment by rokroskar** [comment]
@minrk here's a full example of my `.pre-commit-config.yaml` file:

```
repos:
-   repo: local
    hooks:
    - id: chartpress
      name: chartpress reset
      files: helm-chart/*
      description: Run `chartpress --reset` to clean up helm charts before committing.
      entry: pipenv run chartpress --reset
      language: system
      pass_filenames: false
```

The result is something like this:

```
# rendering the chart
$ chartpress

# trying to commit
git commit -am 'bla'
chartpress reset.........................................................Failed
hookid: chartpress

Files were modified by this hook. Additional output:

$> git log -n 1 --pretty=format:%h -- . . jupyterhub singleuser
$> git log -n 1 --pretty=format:%h -- . chartpress.yaml
$> git log -n 1 --pretty=format:%h -- jupyterhub jupyterhub chartpress.yaml
$> git log -n 1 --pretty=format:%h -- git-clone git-clone chartpress.yaml
Updating helm-chart/renku-notebooks/values.yaml: image: {'repository': 'renku/renku-notebooks', 'tag': 'latest'}
Updating helm-chart/renku-notebooks/values.yaml: jupyterhub.hub.image: {'repository': 'renku/jupyterhub-k8s', 'tag': 'latest'}
Updating helm-chart/renku-notebooks/values.yaml: git_clone.image: {'repository': 'renku/git-clone', 'tag': 'latest'}
```

**Comment by consideRatio** [comment]
`chartpress --reset` is or at least should have very high performance. It will probably be about as easy to setup a local hook as it would be to declare one in this repo though right, since it is just a one liner. From the example you provided, it seems like it makes a lot of sense to use a local hook, as there are some local chart configuration matters as well.

@rokroskar perhaps we could have this local hook example documented in the readme? What do you think?

```yaml
repos:
-   repo: local
    hooks:
    - id: chartpress
      name: chartpress reset
      files: helm-chart/*
      description: Run `chartpress --reset` to clean up helm charts before committing.
      entry: pipenv run chartpress --reset
      language: system
      pass_filenames: false
```
