### ISSUE TITLE
Support extraContainers k8s container spec with valuesPath

### ISSUE THREAD

**Issue by ryanlovett** [jupyterhub/chartpress#39]
I'm not sure if this is what chartpress is intended to do, but I'd like to try using chartpress to build an image defined in our jupyterhub.hub.extraContainers. extraContainers takes a list of dictionaries [where each has an `image` key](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/doc/source/advanced.md#hubextracontainers) with value of the form name:tag. However valuesPath will insert `name` and `tag` keys.

**Comment by consideRatio** [comment]
I think if you configure chartpress.yaml with a valuesPath for an image, it will build and update that path in your chart's values.yaml file with a string formatted like `name:tag` like you wish for.

To use valuesPath to target the specific extraContainers entry, which [is an array](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/values.yaml#L227), you will need @minrk's latest PR merged though, in #63.

```yaml
# what I think could work out after #63 for your situation
charts:
  - name: jupyterhub
    images:
      myextraimg:
        valuesPath: jupyterhub.hub.extraContainers.0.image
```
